Update patch set 2
Patch Set 2:

Removing geventhttpclient for python3 which seem to cause issues.

ERROR: opserver 0.1.dev0 has requirement gevent<1.3, but you'll have gevent 1.5a1 which is incompatible.
ERROR: pycassa 1.11.2 has requirement thrift==0.9.3, but you'll have thrift 0.11.0 which is incompatible.

Patch-set: 2
Reviewer: Gerrit User 16 <16@c72cd27d-1743-4a55-84a4-cd13b8400c52>