Fix missing pip (ci-test-ansible-lint-centos-7)
For ci-test-ansible-lint-centos-7:
START: [untrusted : review.opencontrail.org/Juniper/
contrail-zuul-jobs/tests/ansible-lint.yaml@master]
[...]
TASK [install test requirements]
ERROR: Unable to find any of pip2, pip to use.
pip needs to be installed.

Change-Id: Iab7138457d89b263132931d65e7a9e1471cdb7d6
Partial-Jira-bug: JCB-176497